coverage:
    range: 95..100
    round: nearest
    precision: 2

ignore:
    - "src/Dto/*.php"
    - "src/Kernel.php"
    - "src/EvaluatorBundle.php"
    - "**/*Dto.php"
    - "**/*Collection.php"
    - "**/*ConfigurationProvider.php"
    - "src/ReleaseApp/Domain/Entities/*"
    - "src/ReleaseApp/Infrastructure/Client/Request/*"
    - "src/ReleaseApp/Infrastructure/Client/Response/*"
    - "src/ReleaseApp/Domain/Client/Response/*"
    - "bin"
    - "tests"
    - "**/*.md"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.json"
    - "**/*.xml"
    - "**/*.lock"
