parameters:
    env(EVALUATOR_PROJECT_DIR): '/data'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%env(EVALUATOR_PROJECT_DIR)%'

    SprykerSdk\Evaluator\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    SprykerSdk\Evaluator\Checker\CheckerRegistry:
        arguments:
            - - '@SprykerSdk\Evaluator\Checker\ExampleChecker\ExampleChecker'
