imports:
    - {resource: checkers.yaml}

parameters:
    env(EVALUATOR_PROJECT_DIR): ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDirEnv: '%env(EVALUATOR_PROJECT_DIR)%'

    SprykerSdk\Evaluator\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    symfony.console.application:
        class: Symfony\Bundle\FrameworkBundle\Console\Application
        arguments:
            - '@kernel'

    SprykerSdk\Evaluator\Checker\CheckerRegistry:
        arguments:
            - - '@SprykerSdk\Evaluator\Checker\PhpVersionChecker\PhpVersionChecker'
              - '@SprykerSdk\Evaluator\Checker\SecurityChecker\SecurityChecker'

    SprykerSdk\Evaluator\Checker\PhpVersionChecker\CheckerStrategy\SdkPhpVersionStrategy:
        arguments: [ '%php_version_checker_sdk_versions%' ]

    SecurityChecker\Command\SecurityCheckerCommand:

    # Checkers

    SprykerSdk\Evaluator\Checker\PhpVersionChecker\PhpVersionChecker:
        arguments:
            - '@SprykerSdk\Evaluator\Resolver\PathResolver'
            - '%php_version_checker_allowed_php_versions%'
            - - '@SprykerSdk\Evaluator\Checker\PhpVersionChecker\CheckerStrategy\CurrentPhpVersionStrategy'
              - '@SprykerSdk\Evaluator\Checker\PhpVersionChecker\CheckerStrategy\ComposerPhpVersionStrategy'
              - '@SprykerSdk\Evaluator\Checker\PhpVersionChecker\CheckerStrategy\DeployYamlFilesPhpVersionStrategy'
              - '@SprykerSdk\Evaluator\Checker\PhpVersionChecker\CheckerStrategy\SdkPhpVersionStrategy'
            - '%php_version_checker_doc_url%'

    SprykerSdk\Evaluator\Checker\SecurityChecker\SecurityChecker:
        arguments:
            - '@symfony.console.application'
            - '@SprykerSdk\Evaluator\Resolver\PathResolver'
            - '%security_checker_doc_url%'
