imports:
    - {resource: checkers.yaml}

parameters:
    env(EVALUATOR_PROJECT_DIR): ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDirEnv: '%env(EVALUATOR_PROJECT_DIR)%'

    SprykerSdk\Evaluator\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    SprykerSdk\Evaluator\Checker\CheckerRegistry:
        arguments:
            - - '@SprykerSdk\Evaluator\Checker\ExampleChecker\ExampleChecker'
              - '@SprykerSdk\Evaluator\Checker\PhpVersionChecker\PhpVersionChecker'
              - '@SprykerSdk\Evaluator\Checker\DependencyProviderAdditionalLogicChecker\DependencyProviderAdditionalLogicChecker'

    SprykerSdk\Evaluator\Checker\PhpVersionChecker\CheckerStrategy\SdkPhpVersionStrategy:
        arguments: [ '%php_version_checker_sdk_versions%' ]

    SprykerSdk\Evaluator\Checker\PhpVersionChecker\PhpVersionChecker:
        arguments:
            - '%php_version_checker_allowed_php_versions%'
            - - '@SprykerSdk\Evaluator\Checker\PhpVersionChecker\CheckerStrategy\CurrentPhpVersionStrategy'
              - '@SprykerSdk\Evaluator\Checker\PhpVersionChecker\CheckerStrategy\ComposerPhpVersionStrategy'
              - '@SprykerSdk\Evaluator\Checker\PhpVersionChecker\CheckerStrategy\DeployYamlFilesPhpVersionStrategy'
              - '@SprykerSdk\Evaluator\Checker\PhpVersionChecker\CheckerStrategy\SdkPhpVersionStrategy'

    # Third-party
    PhpParser\ParserFactory: ~
    Symfony\Component\Finder\Finder: ~
